### ISSUE TITLE
Načtení IdP metadat

### ISSUE THREAD

**Issue by smarek** [otevrenamesta/node-nia-connector#2]
jeden z konfiguračních parametrů NIA by měla být URL adresa k metadatům IdP, kvůli získání aktuálních URL adres SSO/SLO a validaci že lokálně známý certifikát IdP souhlasí (případně, že alespoň souhlasí CA, tj. PostSignum)

Případně konfigurační pár URL metadat a CRT očekávaný IdP certifikát

**Comment by vencax** [comment]
URL konfigurovatelne je: https://github.com/otevrenamesta/node-nia-connector/blob/master/idp_metadata.js#L6
ale ty myslis jeste nejaky check toho co se z nej stahne, ze?

**Comment by smarek** [comment]
Aha, díky, v tom případě do readme prosím :)
A druhá část připomínky byla k certificate-pinningu, ale to můžeme vyřešit v #3 
Kdyžtak zavři tento až bude dokumentace, děkuji

**Comment by vencax** [comment]
https://github.com/otevrenamesta/node-nia-connector/commit/c0680c793072c8290b2fb686cd4d4a017b6ff9ce
